libfive/libfive

- bind/guile/test/mesh-test-suite.scm
- doc/references.md
- kernel/include/ao/kernel/format/contours.hpp
- kernel/include/ao/kernel/format/mesh.hpp
- kernel/include/ao/kernel/render/octree.hpp
- kernel/include/ao/kernel/render/quadtree.hpp
- kernel/include/ao/kernel/render/region.hpp
- kernel/include/ao/kernel/render/xtree.hpp
- kernel/include/ao/kernel/render/xtree.ipp
- kernel/src/render/dc.cpp
- kernel/src/render/dc2d.cpp
- kernel/src/render/octree.cpp
- kernel/src/render/quadtree.cpp
- kernel/src/render/region.cpp
- kernel/test/dc.cpp
- kernel/test/octree.cpp
- kernel/test/region.cpp
This PR dramatically improves meshing performance and quality.
It's based on a close reading of [Dual Contouring: The Secret Sauce](https://people.eecs.berkeley.edu/~jrs/meshpapers/SchaeferWarren2.pdf) and implements everything but the QR triangular form (choosing instead to use doubles over floats, since RAM is cheap).
The PR also removes the `XTree` flags for `COLLAPSE` (because there was no good use case for it) and `JITTER` (because the more numerically stable algorithm made it unnecessary; also because it was a bad idea to begin with).
> Better dual contouring

- kernel/include/ao/kernel/eval/evaluator.hpp
- kernel/include/ao/kernel/render/heightmap.hpp
- kernel/src/eval/evaluator.cpp
- kernel/src/render/heightmap.cpp
- ui/include/ao/ui/gl/frame.hpp
- ui/include/ao/ui/worker.hpp
- ui/src/gl/frame.cpp
- ui/src/worker.cpp
This makes the UI faster by saving and re-using `Evaluator` objects for a given `Tree` (rather than reconstructing them whenever the rotation matrix changed).
> Longlived evaluator

- kernel/include/ao/kernel/eval/evaluator.hpp
- kernel/include/ao/kernel/eval/result.hpp
- kernel/include/ao/kernel/tree/cache.hpp
- kernel/include/ao/kernel/tree/opcode.hpp
- kernel/include/ao/kernel/tree/tree.hpp
- kernel/src/eval/evaluator.cpp
- kernel/src/eval/result.cpp
- kernel/src/tree/cache.cpp
- kernel/src/tree/opcode.cpp
- kernel/src/tree/tree.cpp
- kernel/test/cache.cpp
- kernel/test/eval.cpp
- kernel/test/tree.cpp
This PR adds a new opcode, `VAR`, which reflects an independent variable with some default value.  It also adds `Evaluator::gradient`, which returns the gradient with respect to all `VAR` clauses, and `Evaluator::setVar` to change a value.
This is laying the groundwork for a gradient-descent based constraint solver.
> Add variables and gradient calculation

- kernel/include/ao/kernel/eval/result.hpp
Uses a custom allocator to ensure alignment of AVX data, which wasn't the case on Linux previously.
Should fix issue #24.
> Aligned allocator

- studio/include/studio/settings.hpp
- studio/include/studio/shape.hpp
- studio/src/editor.cpp
- studio/src/settings.cpp
- studio/src/shape.cpp
- studio/src/view.cpp
This PR uses `Kernel::findBounds` to automatically extract bounds for shapes (if "autobounds" is checked in the settings pane).  The auto-extracted bounds are used if they're within 1000x of the manually-specified bounds, to work around cases where `findBounds` overestimates by huge amounts.
The rendered bounding boxes accurately reflect the bounds used in meshing, so it's easy to debug and see how well `findBounds` is doing.
This change breaks compatibility of the `#! RENDER ...` comment, which should be manually edited to add a trailing ` / 1 `, e.g.
```#! RENDER -1.3 -0.7 -4.7 / 1.3 0.8 1 / 1 / 1 !#```
should become
```#! RENDER -1.3 -0.7 -4.7 / 1.3 0.8 1 / 1 / 1 / 1 !#```
(you could also add a trailing ` / 0 ` instead, to disable this feature)
> Add automatic bounds checking

- CMakeLists.txt
- studio/src/documentation.cpp
- studio/src/interpreter.cpp
- studio/src/settings.cpp
- studio/src/view.cpp
- studio/src/window.cpp
Hi,
This PR "backports" Studio to Qt 5.6-compatible syntax (from the existing Qt 5.7 syntax) to enable building with Qt 5.6 and also includes a small compiler flag addition to enable compilation on older Mac OS X versions (e.g. 10.8.5).
One benefit from being Qt 5.6-compatible is that that version is a ["Long Term Support" release supported until March 16, 2019](http://doc.qt.io/qt-5/supported-platforms-and-configurations.html#qt-5-6) whereas [Qt 5.7 official support finished June 15, 2017](http://doc.qt.io/qt-5/supported-platforms-and-configurations.html#qt-5-7).
(The next [LTS release is Qt 5.9 until May 31, 2020](http://doc.qt.io/qt-5/supported-platforms-and-configurations.html#qt-5-9) but that drops support for Mac OS X 10.8 & 10.9.)
Working on the assumption that the plans for Studio …
> Add support for Qt 5.6 (and older Mac OS X) for Studio

- libfive/src/eval/eval_deriv_array.cpp
(As per <https://eigen.tuxfamily.org/dox/structEigen_1_1EigenBase.html#ab75c2d8a783d055db397319c5a330eee>)
Example occurrence:
```
/<path>/libfive/src/eval/eval_deriv_array.cpp:34:26: warning: 
comparison of integers of different signs: 'unsigned int' and 'Index' (aka 'int') [-Wsign-compare]
for (unsigned i=0; i < d.rows(); ++i)
~ ^ ~~~~~~~~
```
Test suite passes with this change.
> Fix warning by using correct type (`Eigen::Index` vs `unsigned`).

- libfive/bind/csg.scm
Just found a subtle but important oversight in how I'd written blend-difference; it worked fine if used alone, but if nested, subsequent ones would be added instead of subtracted because the signs were reversed. This should be right now, sorry about the mistake; a function like this is a bit abstract to be sure about at a glance. :)
(I also got rid of the extraneous zero while I was in there.)
> Fix for blend-difference

- libfive/bind/csg.scm
As discussed in https://github.com/libfive/libfive/pull/101 , this just saves some typing in the case of wanting to change how closely the hole fits with the shape it's based on.
> Add optional clearance to blend-difference

- libfive/bind/csg.scm
- Removes `blend-poly`, since it was seemingly incompatible with the auto-bounds system
- Replaces it with `blend-expt`, which has yet to demonstrate any downsides (beyond being 50% slower than `blend-rough`)
- Aliases `blend` to `blend-expt-unit`, which transforms the `m` term to produce similar-looking results to if that value had been passed to `blend-rough`
Let me know if there's anything you'd prefer to have done differently. Also let me know what needs to be done to change the description of `blend-rough` that appears in the shape reference window, as it's not correct, but I can't find where the program is drawing its current description from...
> Replace blend-poly with blend-expt-unit

- studio/src/view.cpp
Fixed the check for the GL context in redrawPicker.
Fixes issue #93.
> Fix to GL context check.

- studio/gl/bars.frag
- studio/gl/basic.frag
- studio/gl/basic.vert
- studio/gl/busy.frag
- studio/gl/line.vert
- studio/src/main.cpp
This enables the OpenGL version check to pass on Mac OS X 10.8 (see #113).
Note:
We don't change the shader language version because apparently Mac OS X "mostly" supports GLSL 3.30 as well. And changing the shader version to 1.50 doesn't work due to use of `location`.
It's possible this "version mismatch" could cause issues on other systems but, you know, WFM. :)
(Ideally we'd handle this without the version mismatch but other approaches I can think of seem more complicated...)
> Use OpenGL 3.2 rather than 3.3.

- libfive/src/render/brep/xtree.cpp
@mkeeter ran into a few issues where verts w/ infinite positions were happening & fixed it by changing this check to `!std::isfinite`  instead of `std::isnan` -- ditto for checking `dv`
> change isnan check to !isfinite

- studio/src/window.cpp
fixes #107 
The windowModified mechanism is now working on Linux and shows an '*' when the windowModified property is true.
> set window title with [*] placeholder on linux

- libfive/include/libfive/tree/archive.hpp
- libfive/include/libfive/tree/deserializer.hpp
- libfive/include/libfive/tree/oracle_clause.hpp
- libfive/include/libfive/tree/serializer.hpp
- libfive/include/libfive/tree/transformed_oracle_clause.hpp
- libfive/include/libfive/tree/tree.hpp
- libfive/src/CMakeLists.txt
- libfive/src/libfive.cpp
- libfive/src/tree/deserializer.cpp
- libfive/src/tree/oracle_clause.cpp
- libfive/src/tree/serializer.cpp
- libfive/src/tree/transformed_oracle_clause.cpp
- libfive/src/tree/tree.cpp
- libfive/test/archive.cpp
- libfive/test/tree.cpp
This moves serialization and deserialization out of the Archive class (which becomes a bag of labelled shapes), and cleans up the API for Oracles to serialize/deserialize themselves.
> Rewrite serialization + deserialization

- libfive/src/eval/eval_interval.cpp
This was an issue that I ran into compiling on Ubuntu 18.04, everything up-to-date. Looked into the code, this is what needed to be fixed on my end. If this passes compilation on MacOS as well, then I'd say merge the changes into master.
> isnan() changed to std::isnan() to fix compilation

- libfive/bind/libfive-guile.cpp
This PR exports `<shape>` so it can be used as a class outside the libfive package.
Currently if you first do this [procedure](https://github.com/libfive/libfive/blob/master/doc/guide.md#working-from-the-guile-command-line),
then:
(use-modules (oop goops))
Now try to define a method:
(define-method (shape->mesh-data (s <shape>)
(r <list>)
(res <number>))
(format #t "shape: ~a region: ~a resolution: ~a~%" s r res))
Guile returns:
...In procedure module-lookup: Unbound variable: <shape>...
After applying this PR, the method can be defined and works.
> Fix apparent typo in libfive Guile module.

- libfive/include/libfive.h
Caught invalid struct referencing when using C header analyzing [program](https://github.com/rpav/c2ffi) and I thought it would be worthwhile to share the findings.
> Fix libfive.h struct definitions to conform to C standard

- libfive/include/libfive.h
- libfive/src/libfive.cpp
This alternate mesh format is directly supported in Open Inventor (e.g. the ```SoIndexedFaceSet``` node class).  This will allow  the Clive, PyInventor, and Pivy Open Inventor bindings to use Libfive C API meshes without conversion.
> Added 'libfive_mesh_coords' alternate mesh format to the C API.

- CMakeLists.txt
My apologies this PR contains several features, but I was rushing through night to build `libfive` in GNU environments on Win/Linux/macOS so there's that:
* Allow disabling Studio build
* Ensure provided CXX flags are applied and not overwritten
* Update build for MinGW on Windows
So, in the end, I've managed to build `libfive` with Travis and Appveyor on all those platforms in GNU(-like) environments (Ubuntu Xenial with GCC8, macOS with Apple's Clang, Windows with msys2's MinGW). 
If you are interested I can create separate PR with Travis and Appveyor configs tailored specifically to build `libfive`.
> Studio build switch, proper CXX flags handling and MinGW build

- libfive/bind/text.scm
- libfive/test/guile.cpp
This should fix #161 . The locale encoding is set to "en_US.UTF-8" so that the C string for the "text.scm" binding is evaluated correctly in  [libfive-guile.cpp](https://github.com/libfive/libfive/blob/master/libfive/bind/libfive-guile.cpp).
> set locale encoding to prevent degree symbol from breaking unit tests

- libfive/include/libfive.h
- libfive/src/libfive.cpp
This alternate contour format is directly supported in Open Inventor (e.g. the SoLineSet node class). This will allow the Clive, PyInventor, and Pivy Open Inventor bindings to use Libfive C API contours without conversion.
>  Added 'libfive_contours3' alternate contour format to the C API. 

- bin/export-meshes
This fixes #235. Please make sure the script still works on your system, as I'm not sure since what version of the coreutils the `-S` option exists.
> Fixed env error in export-meshes

- CMakeLists.txt
- libfive/include/libfive/oracle/transformed_oracle_clause.hpp
- libfive/src/oracle/transformed_oracle_clause.cpp
- libfive/src/render/brep/dc/dc_tree2.cpp
- libfive/test/archive.cpp
Hey Matt,
I got two errors when trying to build libfive using g++ on my Mac.
1. An unsupported flag `-stdlib=libc++` was used. This happened since the root CMakeLists.txt equated using a Mac with using clang. My fix assumes you meant to test for clang and Mac, but you could change it to `${CMAKE_CXX_COMPILER_ID} MATCHES "AppleClang"` instead.
2. There were symbols with multiple definitions since `XTree<2, DCTree<2>, DCLeaf<2>>` was instantiated in both `dc_tree2.cpp` and `dc_xtree.cpp`. This is fixed by removing the instantiation in `dc_tree2.cpp`, which doesn't seem to be used.
I also removed some unnecessary semicolons that were generating warnings (as a result of compiling with `-pedantic`).
I built and tested this branch using three different configurations. On mac with clang, one …
> Fix gcc on mac

- libfive/src/CMakeLists.txt
- libfive/src/version.cmake
Currently the git commands used to generate `version.c` are run from the build directory, which might not be a subdirectory of the libfive repo. I propose running them from the source directory instead.
I noticed this since I'm building libfive as a submodule, and it was picking up the parent project's hash and branch. Even when libfive isn't a submodule, now the git info won't end up being "N/A" if the build dir is outside the repo.
> Find git hash for truly out of source builds

- studio/src/window.cpp
This sets up the file filters properly and also adds a filter for "any files". The file extension is added automatically in the file save dialog, so the conditional block isn't necessary anymore.
It also adds two shortcuts for exporting STL files Ctrl+E (used widely in programs to export files) and F7 (which is the shortcut to export STLs in OpenSCAD).
> Set save/export filters and add export shortcuts

- libfive/include/libfive/render/brep/dual.hpp
- libfive/include/libfive/render/brep/per_thread_brep.hpp
- libfive/include/libfive/render/brep/progress.hpp
- libfive/include/libfive/render/brep/simplex/simplex_tree.hpp
- libfive/src/render/brep/simplex/simplex_tree.cpp
changed atomic_uint32t and atomic_uint64t to atomic<uint32t> and atomic<uint64t> respectively
now compiles with GCC 6 on Debian GNU/Linux
> refactoring atomic types for compilation with GCC

- .travis.yml
- .travis/Dockerfile
- .travis/build-docker.sh
- .travis/run-tests.sh
This patch set creates a CI system that installs dependencies, compiles libfive, and runs tests.
I have opted for a 'docker-in-docker' approach, because the most recent Ubuntu release supported by Travis is Ubuntu 16.04, and it is difficult to get the correct version of Guile 2.2 and Qt5 on that version. Therefore, I create a docker image with Ubuntu 18.04. I followed a similar approach to this blog post: https://agateau.com/2019/building-qt-apps-with-travis-and-docker/
Presently, the CI has two failing tests, and a number of compile warnings. See https://travis-ci.com/nickodell/libfive/builds/114044703 for details.
Fixes #255
> Set up Travis CI support

- libfive/include/libfive/render/brep/dc/intersection.hpp
- libfive/src/render/brep/manifold_tables.cpp
As discussed in https://github.com/libfive/libfive/issues/279.
Two tests fail, and two fail as expected, which is also the behavior I see on master.
> Compatibility with Boost 1.70

- libfive/include/libfive/render/brep/vol/vol_tree.hpp
Ran into this on GCC 7.4.0 when trying to upgrade the version in Nixpkgs. Without this, it fails with `error: 'unique_ptr' in namespace 'std' does not name a template type` and likewire for `shared_ptr` at several points.
> Fix unique_ptr/shared_ptr build error

- studio/include/studio/args.hpp
- studio/src/args.cpp
- studio/src/window.cpp
This is a small change I made to Studio because I use a vertical monitor.
Starting with 'Studio --vertical' switches from the default horizontal layout.
This is my first pull request, so let me know if I have done something wrong, or you don't think this feature is required.
> Optional vertical layout for the editor / 3D view.

- libfive/src/tree/cache.cpp
I just noticed that it wouldn't compile on Arch with GCC 9.2.0 and this fixes it. Also tested with latest clang on Arch too.
> Fix missing template arguments for lock

- README.md
- studio/src/documentation.cpp
- studio/src/editor.cpp
This requires Qt 5.11 minimum unfortunately, though it's a LTS release.
[setTabStopDistance](https://doc.qt.io/qt-5/qplaintextedit.html#tabStopDistance-prop) was introduced in 5.10 and [horizontalAdvance](https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance) in 5.11.
Tested on Arch Linux with latest GCC and Clang.
> Change calls to non-deprecated Qt functions

- studio/include/studio/window.hpp
- studio/src/window.cpp
Adds the shortcut Ctrl+Q and the menu option to close the program. 
It's more convenient and makes it possible to close Studio normally with window managers which don't draw any window decorations like i3 or awesome.
> Add quit action (menu and shortcut)

- README.md
- studio/src/documentation.cpp
- studio/src/editor.cpp
Allow building on Ubuntu 18.04 again
This reverts commit da79dd9480c11a660ec29c7ceacecd4fe2a3cda5.
da79dd9480c11a660ec29c7ceacecd4fe2a3cda5 raises the required Qt version to 5.11, past what is available on Ubuntu 18.04 without indicating that Ubuntu 18.04 is no longer supported.
Considering Ubuntu 18.04 is still the current LTS release (and I use it ;-) ) and that given that `QFontMetrics::width` still exists in 5.11 (and beyond) and `QFontMetrics::horizontalAdvance` are exactly equivalent, I would strongly prefer to retain Qt 5.7 compatibility.
I could also rework the pull request to use `QFontMetrics::horizontalAdvance` for qt >= 5.11 and `QFontMetrics::width` for older versions since at some point `QFontMetrics::width` will be removed.
> Revert "Change calls to non-deprecated Qt functions"

- studio/include/studio/view.hpp
After startup the shapes wouldn't render any thing. Selecting
a different mesh algorithm in the UI would fix this issue.
The issue is that the default algorithm is not initialized. This causes
it to be sometimes '0' but sometimes it is just some random data.
When it is random data the shape doesn't get rendered and a nullptr is
being returned.
This patch default initializes the algorithm to "DUAL_CONTOURING"
> FIX no rendering after startup without selecting new render method

- studio/include/studio/window.hpp
- studio/src/window.cpp
Some programs like vim save a temporary file and move it to the new
location.
The QFileSystemWatcher will receive the notification "deleted" on the
current file. It does not notice that a new file is being created.
This patch will also listen to the underlying directory which will also
trigger a reload when a new file is being added. This should make the
file watch function much more robust.i
> FIX: Add file watcher on directory

- studio/src/window.cpp
Some editors replace the file when saving that confuses QtFileSystem watcher and it captures the edition as a file deletion, meaning that it only sends the signal during the first save and then the file is un-watched.
The proposed changes re-watch the file to make sure that it subsequent changes are captured by the watcher.
[The issue can be replicated easily and is well known](https://stackoverflow.com/questions/18300376/qt-qfilesystemwatcher-signal-filechanged-gets-emited-only-once#18304496). My current setup (Linux + NeoVim) only loads once without the changes. After the changes, all editions are captured and the view is re-rendered accordingly.
Thanks
> Correct autoload only running once in some editors

- README.md
- libfive/bind/python/libfive/runner.py
- libfive/bind/python/libfive/shape.py
- studio/include/studio/python/interpreter.hpp
- studio/src/python/interpreter.cpp
This implements direct (push/pull) modeling in Python.
Shapes can be parameterized with free variables using the `var(...)` function.  Before evaluation, we walk the AST and patch these function calls with ID and textual location, so that we can edit the script to substitute in new values.
https://user-images.githubusercontent.com/745333/111542364-feab5080-8747-11eb-80a5-fc904122f278.mov
Luckily, the Scheme implementation was already pretty abstract, so I didn't need to make any changes on the push-pull-edit side, just needed to output the right things from the `Interpreter`.
> Support direct modeling in Python

- libfive/bind/guile/CMakeLists.txt
The normal value of GUILE_CCACHE_DIR is part of a dependency (Guile), which breaks the build on NixOS as that's all purposely kept read-only. This allows overriding it with `-DGUILE_CCACHE_DIR=...` or the like.
> Allow overriding GUILE_CCACHE_DIR

- studio/include/studio/camera.hpp
- studio/include/studio/view.hpp
- studio/src/camera.cpp
- studio/src/window.cpp
Changed the mouse rotation to be responsive to the size of the viewport. This is so that the rotation amount is more intuitive for the size of window/screen. Also toned down the default rotation speed a bit. This is easily controllable with the new Camera::rotationSensitivity variable.
Added a selection drop down to the view menu for selecting between low, medium, and high sensitivities.
A proper slider would be nice in the future for the user to fully customize their sensitivity, but it isn't as easy with the current drop down style settings menu.
> Mouse rotation sensitivity

- studio/include/studio/view.hpp
- studio/include/studio/window.hpp
- studio/src/view.cpp
- studio/src/window.cpp
I've (presumptuously) based the PR on the other one since they're related but I can change that.
The settings keys are in kebab case as was `first-run`. I didn't bother with using string constants (for key and value) since they're used in local contexts where it's easy to check that they're correct.
The concerned signals are changed from `triggered` to `toggled` since this is how we set the default value. One unfortunate consequence is that animation are played based on the default value. Maybe we can disable animations during construction?
I also noticed that the default language is controlled by a commandline flag, but maybe a setting can be added such that CLI flag > setting value > default value?
> Save application settings

- libfive/bind/python/libfive/ffi.py
- libfive/bind/python/libfive/shape.py
I was experimenting with getting to mesh data via Python bindings, needed to add a few types in the process, and thought this might be useful for other people.
> Python bindings: add calls to render mesh

- README.md
- libfive/bind/python/CMakeLists.txt
Check if PYTHON_SITE_PACKAGES_DIR has been defined by the user before
asking Python for the system package library destination such that the
install destination for the Python bindings can be specified using,
e.g.
cmake -DPYTHON_SITE_PACKAGES_DIR=/usr/local/lib/python3.9/dist-packages .
> Check if PYTHON_SITE_PACKAGES_DIR has been defined by the user

- libfive/bind/guile/libfive/kernel.scm
- libfive/bind/guile/libfive/stdlib/text.scm
- libfive/bind/python/libfive/stdlib/text.py
- libfive/stdlib/gen_py.py
Hello!
Just got a couple small bug fixes here.
I think it makes sense to add `shape?` to the available bindings.
The typo is pretty obviously wrong.
As for the `shape-eval` error, it is a little odd.  In `shape-save-mesh` we construct a `libfive-region` using lists instead of `libfive-interval`s so I have some confidence in my fix.
> A couple small bug fixes

- libfive/include/libfive.h
- libfive/src/libfive.cpp
Tested and confirmed only hits 1 core when using `*_st` variant
> Add single-threaded version of libfive_tree_render_mesh

- README.md
Refactor build instructions to target VS2022 due to updated paths and the aging status of VS2019.
> Refactor build instructions for VS2022

- README.md
No matter which version of Ubuntu is used, a C++ compiler is required.
> include C++ compiler in Ubuntu instructions

- CMakeLists.txt
As discussed ... I'd like to have a possibility to switch off the creation of debugging symbols
> Added option to turn off debugging symbols
