libfive/libfive

bind/api.cpp
kernel/include/ao/kernel/eval/clause.hpp
kernel/include/ao/kernel/eval/evaluator.hpp
kernel/include/ao/kernel/tree/atom.hpp
kernel/include/ao/kernel/tree/opcode.hpp
kernel/include/ao/kernel/tree/store.hpp
kernel/include/ao/kernel/tree/token.hpp
kernel/include/ao/kernel/tree/tree.hpp
kernel/src/eval/clause.cpp
kernel/src/eval/evaluator.cpp
kernel/src/tree/atom.cpp
kernel/src/tree/store.cpp
kernel/src/tree/token.cpp
kernel/src/tree/tree.cpp
kernel/test/affine.cpp
kernel/test/eval.cpp
kernel/test/glm.hpp
kernel/test/jit.cpp
kernel/test/matrix.cpp

Represent X, Y, and Z by linear expressions in the form `a*X + b*Y + c*Z + d`.
Then, any linear transform can be represented without making the tree deeper (by making a new `AFFINE` tree with different constants).

Affine representations for coordinates

---

kernel/CMakeLists.txt
kernel/include/ao/kernel/eval/row.hpp
kernel/include/ao/kernel/render/subregion.hpp
kernel/src/eval/evaluator.cpp
kernel/test/avx.cpp
kernel/test/heightmap.cpp
ui/CMakeLists.txt
ui/include/ao/ui/watcher.hpp

doesn't quite run, but at least it builds :)

make it build on linux

---

examples/lsystem.scm

add examples/lsystem.scm

---

bin/ao-guile
bind/guile/ao/bind.scm
bind/libao.cpp
bind/libao.hpp

Block the REPL until the window opens.
Maybe fix mysterious crashes in FFI-land?

Cleaner startup

---

kernel/CMakeLists.txt
kernel/include/ao/kernel/solve/solver.hpp
kernel/src/solve/solver.cpp
kernel/test/solver.cpp

Simple implementation of Newton's method (with backtracking line search).

Root finding

---

ao/bind/shapes.scm

Fixes the circle out of place:

Fix rounded-rectangle lower right corner

---

ao/bind/csg.scm

I don't know if this seems too obvious to be worth including as a default, but it's one I like so I thought I'd offer it!

Add "blend-difference" csg

---

ao/bind/transforms.scm

Just a shorthand, but one I use a lot :)

Add three-axis scale in one function

---

studio/examples/tutorial.io

Not attached to the wording, feel free to modify.
(As per <https://github.com/libfive/libfive/issues/72>)

Mention how to find the additional examples available.

---

libfive/bind/transforms.scm

Just noticed I forgot the [] around the optional arguments in the description, sorry about that!

Fix attract/repel docs

---

libfive/bind/shapes.scm

Another convenience function, I often find myself wanting to tweak the size of boxes while leaving their center in the same place.

Add box-centered

---

libfive/bind/transforms.scm

Here's an effect I realised I was missing for something I wanted to make -- it lets you twirl a shape like spaghetti around a fork, either falling off from a point (`twirl-n`) or from a line (`twirl-axis-n`).
On the fence about the name, will change it if you have suggestions (swirl? curl?)

Add twirls

---

libfive/bind/transforms.scm

This shouldn't change anything on the front end, and was mostly done as an exercise for me, but it should hopefully lay out a useful way of generalizing axis-dependent transformation functions for anyone writing them in the future!
In fact, if I can get the hang of how to pass the remaining arguments through to another function in a generic way (or to pass them as a tuple or something), I bet the `generic-twirl-n` function could be generalized enough to be used for any function like this -- or maybe even to be passed to it as an argument, as in `(rotate-axis (sphere 1) transform-axis-y 2)` rather than `(rotate-y (sphere 1) 2)`? And similarly for the `center` argument... I'm not sure whether that would be simplifying things or complicating them at this point, so it's just an idea for now …

Less redundant definitions for the twirl functions

---

README.md

studio built successfully using these steps on Linux Mint 18.3 (Ubuntu 16.04)

Updated Ubuntu instructions

---

studio/examples/tutorial.io

Small addition to Studio tutorial to make CSG / Guile syntax less intimidating (at least to me). P.S. where are the CSG operations listed out in libfive, and is there a easy to view list of the implemented operations? Searching for "csg" or "CSG" in the source didn't turn anything up.

Added 'Hello word' for CSG to Studio tutorial

---

Dockerfile

I'm also having some trouble with building the C++ on Linux.  This Dockerfile might make it easier to test a Linux build on the Mac.

basic Dockerfile to test ubuntu build

---

libfive/include/libfive/render/brep/neighbors.hpp

Had to include atomic to compile the project.

Add <atomic> include to neighbors.hpp

---

studio/src/view.cpp

Accept mouse(wheel) events

---

libfive/include/libfive/render/brep/object_pool.hpp
libfive/src/render/brep/progress.cpp

Adding include statements for cassert

---

libfive/include/libfive.h
libfive/src/libfive.cpp

This PR basically makes the Evaluator C++ Class accessible from the C Api. Methods provided are for creating an instance of an Evaluator with an initial set of Variables, updating the variables, rendering (just saving mesh to file, is what I needed for now) and deleting the Evaluator instance.

Added support for variables to C api

---

libfive/include/libfive/render/brep/edge_tables.hpp
libfive/include/libfive/render/brep/neighbor_tables.hpp

Explicit instantation declarations for EdgeTables and NeighborTables templates

---

studio/examples/koalahedron.io

Made a shape for generating koalas in Libfive.  Feel free to adjust parameters (e.g. leg position) if you want.  Screen shots from Studio:
Enjoy!

Add koalahedron shape to examples.

---

studio/src/script.cpp

This improves the indentation as described in #70 
The following example can be written without hitting space or tab once.
```
(add 12 23
34 45 (minus
56
67)
17)
```

[FEAT] improved text editor indentation

---

libfive/bind/python/libfive/shape.py

This time I thoroughly checked, should be the last

python: expose last remaining operations

---

studio/include/studio/editor.hpp
studio/include/studio/window.hpp
studio/src/args.cpp
studio/src/editor.cpp
studio/src/window.cpp

Follow-up to the previous PR. The last language used is now also stored in settings

Store last language used in application settings

---

studio/CMakeLists.txt

Fix building with Qt5

---

README.md

i was able to recover the latest commit from GNU Guix (but not the commits) and published it in `recovered` branch

README: New mirror for inspekt3d

---

libfive/include/libfive/render/brep/default_new_delete.hpp

This change has been tested in Curv, and fixes the build bug.

fix bug #522

---

libfive/bind/python/libfive/shape.py

Update call in Python `save_stl` function to utilize `libfive_tree_save_meshes` rather than the older `libfive_tree_save_mesh`, and expose the quality parameter.

Add quality param to python save_stl method

---

libfive/stdlib/stdlib_impl.cpp

Huge bug that took out several hours for me not knowing that underlying code does not work correctly.

delta.z is never used in array_xyz
